name: YUIShop
api: ["1.0.0"]
version: "1.0.0"
load: POSTWORLD
main: yxmingy.uishop.Main
commands:
 shop:
  description: "召唤UI商店"
  usage: "/shop"
  permission: yxmingy.command.uishop
permissions:
 yxmingy.command.uishop: 
  default: true